import type { Sale, SaleLine } from "@/types/db";

export function formatLKR(amount: number): string {
  return `Rs. ${amount.toLocaleString("en-LK", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

// Short, user-facing bill code derived from the sale UUID. Cashiers / customers
// see this code on receipts, and can type it back into the bill lookup search.
export const BILL_CODE_LENGTH = 8;

export function shortBillCode(saleId: string, length: number = BILL_CODE_LENGTH): string {
  return saleId.slice(0, length).toUpperCase();
}

const INSTAGRAM_URL =
  "https://www.instagram.com/polwatta_bbq_house?igsh=MTR6cHFveXlobzczZg%3D%3D&utm_source=qr";
const FACEBOOK_URL =
  "https://www.facebook.com/share/1bPtcSgFV2/?mibextid=wwXIfr";

export interface ReceiptInput {
  saleId: string;
  totalAmount: number;
  items: SaleLine[];
  createdAt?: string;
  paymentMethod?: string;
}

export function buildReceiptText(sale: ReceiptInput): string {
  const date = sale.createdAt ? new Date(sale.createdAt) : new Date();
  const dateStr = date.toLocaleString("en-LK", { hour12: true });
  const paymentMethod = sale.paymentMethod ?? "Cash";

  const lines = [
    `🔥 *පොල්වත්ත FOOD HUB* 🔥`,
    `_Marawila Beachfront_`,
    `------------------------------------------`,
    `📄 *Order:* #${shortBillCode(sale.saleId)}`,
    `📅 *Date:* ${dateStr}`,
    `------------------------------------------`,
    ``,
    ...sale.items.map((i) => {
      const lineTotal = i.price * i.quantity;
      return `📍 *${i.name}* \n   ${i.quantity} x ${formatLKR(i.price)} = *${formatLKR(lineTotal)}*`;
    }),
    ``,
    `------------------------------------------`,
    `💰 *GRAND TOTAL: ${formatLKR(sale.totalAmount)}*`,
    `💳 *Payment:* ${paymentMethod}`,
    `------------------------------------------`,
    ``,
    `🙏 *Thank you for visiting us!*`,
    `Hope to see you again soon at the beachfront.`,
    ``,
    `📱 *Stay Connected:*`,
    `📸 Instagram: ${INSTAGRAM_URL}`,
    `👍 Facebook: ${FACEBOOK_URL}`,
    ``,
    `_Generated by Polwatta POS_`,
  ];

  return lines.join("\n");
}

/**
 * Normalize a Sri Lankan phone to E.164-ish digits for wa.me links.
 * Accepts formats: 0771234567, 771234567, +94771234567, 94771234567
 */
export function normalizeLKPhone(input: string): string | null {
  const digits = input.replace(/\D/g, "");
  if (!digits) return null;

  let normalized = digits;
  if (normalized.startsWith("0")) {
    normalized = "94" + normalized.slice(1);
  } else if (!normalized.startsWith("94")) {
    if (normalized.length === 9) {
      normalized = "94" + normalized;
    }
  }

  // Final sanity: should be 11 digits (94 + 9-digit local)
  if (normalized.length < 10 || normalized.length > 15) return null;
  return normalized;
}

export function buildWhatsAppUrl(phoneInput: string, sale: ReceiptInput): string | null {
  const phone = normalizeLKPhone(phoneInput);
  if (!phone) return null;
  // Use api.whatsapp.com/send instead of wa.me — wa.me does a 302 redirect that
  // can mangle 4-byte UTF-8 emoji sequences (showing as � in delivered messages)
  // while 3-byte sequences (e.g. Sinhala) survive.
  return `https://api.whatsapp.com/send?phone=${phone}&text=${encodeURIComponent(buildReceiptText(sale))}`;
}

export function buildSmsUrl(phoneInput: string, sale: ReceiptInput): string | null {
  const phone = normalizeLKPhone(phoneInput);
  if (!phone) return null;
  return `sms:+${phone}?body=${encodeURIComponent(buildReceiptText(sale))}`;
}
