"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Bell, ShoppingBag, Wallet, Package, X } from "lucide-react";
import type {
  RealtimePostgresInsertPayload,
  RealtimePostgresUpdatePayload,
} from "@supabase/supabase-js";
import { createClient } from "@/lib/supabase/client";
import { cn } from "@/lib/utils";
import type { Notification, NotificationType } from "@/types/db";

const DROPDOWN_LIMIT = 10;

export function NotificationBell() {
  const supabase = useMemo(() => createClient(), []);
  const [items, setItems] = useState<Notification[]>([]);
  const [unreadCount, setUnreadCount] = useState(0);
  const [open, setOpen] = useState(false);
  const [marking, setMarking] = useState(false);
  const [clearing, setClearing] = useState(false);
  const wrapperRef = useRef<HTMLDivElement>(null);
  // Resolved once on mount so realtime callbacks can read the latest value
  // without re-subscribing whenever the user changes.
  const userIdRef = useRef<string | null>(null);

  // Resolve the current user id once on mount.
  useEffect(() => {
    let cancelled = false;
    (async () => {
      const { data } = await supabase.auth.getUser();
      if (cancelled) return;
      userIdRef.current = data.user?.id ?? null;
    })();
    return () => {
      cancelled = true;
    };
  }, [supabase]);

  // Initial fetch: latest 10 notifications + total unread count. RLS already
  // hides self-actions and dismissed rows; we apply the same actor filter
  // client-side as a defensive fallback in case auth state lags behind.
  useEffect(() => {
    let cancelled = false;

    (async () => {
      const [listRes, countRes] = await Promise.all([
        supabase
          .from("notifications")
          .select("*")
          .order("created_at", { ascending: false })
          .limit(DROPDOWN_LIMIT),
        supabase
          .from("notifications")
          .select("id", { count: "exact", head: true })
          .eq("is_read", false),
      ]);

      if (cancelled) return;

      const myId = userIdRef.current;
      if (listRes.data) {
        const rows = (listRes.data as Notification[]).filter(
          (n) => !myId || n.actor_id !== myId,
        );
        setItems(rows);
      }
      if (typeof countRes.count === "number") setUnreadCount(countRes.count);
    })();

    return () => {
      cancelled = true;
    };
  }, [supabase]);

  // Realtime: react to inserts (new notification) and updates (mark-as-read).
  useEffect(() => {
    const channel = supabase
      .channel("admin-notifications")
      .on(
        "postgres_changes",
        { event: "INSERT", schema: "public", table: "notifications" },
        (payload: RealtimePostgresInsertPayload<Notification>) => {
          const incoming = payload.new;
          // Defensive: skip notifications generated by the current admin.
          // RLS should already exclude these, but realtime broadcasts can
          // race with auth state on first load.
          const myId = userIdRef.current;
          if (myId && incoming.actor_id === myId) return;

          setItems((prev) => {
            if (prev.some((n) => n.id === incoming.id)) return prev;
            return [incoming, ...prev].slice(0, DROPDOWN_LIMIT);
          });
          if (!incoming.is_read) {
            setUnreadCount((prev) => prev + 1);
          }
        },
      )
      .on(
        "postgres_changes",
        { event: "UPDATE", schema: "public", table: "notifications" },
        (payload: RealtimePostgresUpdatePayload<Notification>) => {
          const updated = payload.new;
          // The notifications table does not use REPLICA IDENTITY FULL, so
          // payload.old only contains the primary key. Derive the previous
          // is_read value from the locally cached row instead.
          setItems((prev) => {
            const prior = prev.find((n) => n.id === updated.id);
            if (prior && prior.is_read !== updated.is_read) {
              setUnreadCount((c) =>
                updated.is_read ? Math.max(0, c - 1) : c + 1,
              );
            }
            return prev.map((n) =>
              n.id === updated.id ? { ...n, ...updated } : n,
            );
          });
        },
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [supabase]);

  // Outside-click + Escape close.
  useEffect(() => {
    if (!open) return;

    function handlePointer(event: MouseEvent) {
      if (!wrapperRef.current) return;
      if (!wrapperRef.current.contains(event.target as Node)) {
        setOpen(false);
      }
    }
    function handleKey(event: KeyboardEvent) {
      if (event.key === "Escape") setOpen(false);
    }

    document.addEventListener("mousedown", handlePointer);
    document.addEventListener("keydown", handleKey);
    return () => {
      document.removeEventListener("mousedown", handlePointer);
      document.removeEventListener("keydown", handleKey);
    };
  }, [open]);

  const markAllRead = useCallback(async () => {
    if (unreadCount === 0 || marking) return;
    setMarking(true);
    const { error } = await supabase
      .from("notifications")
      .update({ is_read: true })
      .eq("is_read", false);
    setMarking(false);
    if (error) return;

    setItems((prev) => prev.map((n) => ({ ...n, is_read: true })));
    setUnreadCount(0);
  }, [marking, supabase, unreadCount]);

  const dismiss = useCallback(
    async (id: string) => {
      const userId = userIdRef.current;
      if (!userId) return;

      let wasUnread = false;
      setItems((prev) => {
        const target = prev.find((n) => n.id === id);
        wasUnread = !!target && !target.is_read;
        return prev.filter((n) => n.id !== id);
      });
      if (wasUnread) setUnreadCount((c) => Math.max(0, c - 1));

      const { error } = await supabase
        .from("notification_dismissals")
        .insert({ notification_id: id, user_id: userId });
      if (error) {
        // Best-effort rollback: refetch to resync.
        const { data } = await supabase
          .from("notifications")
          .select("*")
          .order("created_at", { ascending: false })
          .limit(DROPDOWN_LIMIT);
        if (data) {
          const myId = userIdRef.current;
          setItems(
            (data as Notification[]).filter(
              (n) => !myId || n.actor_id !== myId,
            ),
          );
        }
      }
    },
    [supabase],
  );

  const dismissAll = useCallback(async () => {
    const userId = userIdRef.current;
    if (!userId || items.length === 0 || clearing) return;
    setClearing(true);

    const rows = items.map((n) => ({
      notification_id: n.id,
      user_id: userId,
    }));
    const dismissedUnread = items.filter((n) => !n.is_read).length;

    setItems([]);
    setUnreadCount((c) => Math.max(0, c - dismissedUnread));

    const { error } = await supabase
      .from("notification_dismissals")
      .insert(rows);
    setClearing(false);
    if (error) {
      const { data } = await supabase
        .from("notifications")
        .select("*")
        .order("created_at", { ascending: false })
        .limit(DROPDOWN_LIMIT);
      if (data) {
        const myId = userIdRef.current;
        setItems(
          (data as Notification[]).filter(
            (n) => !myId || n.actor_id !== myId,
          ),
        );
      }
    }
  }, [clearing, items, supabase]);

  const displayCount = unreadCount > 9 ? "9+" : String(unreadCount);

  return (
    <div ref={wrapperRef} className="relative">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        aria-label={
          unreadCount > 0
            ? `Notifications (${unreadCount} unread)`
            : "Notifications"
        }
        aria-haspopup="menu"
        aria-expanded={open}
        className={cn(
          "relative inline-flex h-9 w-9 items-center justify-center rounded-lg",
          "text-stone-700 hover:bg-stone-100 transition-colors",
          "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 focus-visible:ring-offset-2",
        )}
      >
        <Bell size={18} />
        {unreadCount > 0 && (
          <span
            className={cn(
              "absolute -top-0.5 -right-0.5 min-w-[18px] h-[18px] px-1",
              "rounded-full bg-red-600 text-white text-[10px] font-bold leading-[18px]",
              "ring-2 ring-white text-center",
            )}
          >
            {displayCount}
          </span>
        )}
      </button>

      {open && (
        <div
          role="menu"
          className={cn(
            "absolute right-0 mt-2 w-80 sm:w-96 z-50",
            "rounded-xl border border-stone-200 bg-white shadow-lg",
            "overflow-hidden",
          )}
        >
          <div className="flex items-center justify-between px-4 py-3 border-b border-stone-100">
            <div className="font-semibold text-stone-900 text-sm">
              Notifications
            </div>
            <div className="flex items-center gap-3">
              <button
                type="button"
                onClick={markAllRead}
                disabled={unreadCount === 0 || marking}
                className={cn(
                  "text-xs font-medium",
                  unreadCount === 0 || marking
                    ? "text-stone-400 cursor-not-allowed"
                    : "text-brand-700 hover:text-brand-800",
                )}
              >
                Mark all as read
              </button>
              <span className="text-stone-300 text-xs">·</span>
              <button
                type="button"
                onClick={dismissAll}
                disabled={items.length === 0 || clearing}
                className={cn(
                  "text-xs font-medium",
                  items.length === 0 || clearing
                    ? "text-stone-400 cursor-not-allowed"
                    : "text-stone-700 hover:text-stone-900",
                )}
              >
                Clear all
              </button>
            </div>
          </div>

          {items.length === 0 ? (
            <div className="px-4 py-8 text-center text-sm text-stone-500">
              No notifications yet.
            </div>
          ) : (
            <ul className="max-h-96 overflow-y-auto divide-y divide-stone-100">
              {items.map((n) => (
                <NotificationRow
                  key={n.id}
                  notification={n}
                  onDismiss={dismiss}
                />
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
}

function NotificationRow({
  notification,
  onDismiss,
}: {
  notification: Notification;
  onDismiss: (id: string) => void;
}) {
  const tone = TYPE_TONES[notification.type];
  const Icon = tone.icon;

  return (
    <li
      className={cn(
        "group relative flex gap-3 px-4 py-3",
        !notification.is_read && "bg-brand-50/60",
      )}
    >
      <div
        className={cn(
          "mt-0.5 w-8 h-8 rounded-full grid place-items-center flex-shrink-0",
          tone.iconBg,
          tone.iconFg,
        )}
      >
        <Icon size={16} />
      </div>
      <div className="min-w-0 flex-1 pr-6">
        <div className="flex items-center gap-2">
          <span className="font-medium text-sm text-stone-900 truncate">
            {notification.title}
          </span>
          {!notification.is_read && (
            <span className="w-2 h-2 rounded-full bg-red-500 flex-shrink-0" />
          )}
        </div>
        <p className="text-xs text-stone-600 mt-0.5 break-words">
          {notification.message}
        </p>
        <p className="text-[11px] text-stone-400 mt-1">
          {formatRelativeTime(notification.created_at)}
        </p>
      </div>
      <button
        type="button"
        onClick={() => onDismiss(notification.id)}
        aria-label="Dismiss notification"
        className={cn(
          "absolute top-2 right-2 inline-flex h-6 w-6 items-center justify-center",
          "rounded-md text-stone-400 hover:text-stone-700 hover:bg-stone-100",
          "opacity-0 group-hover:opacity-100 focus-visible:opacity-100 transition-opacity",
          "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500",
        )}
      >
        <X size={14} />
      </button>
    </li>
  );
}

const TYPE_TONES: Record<
  NotificationType,
  {
    icon: typeof ShoppingBag;
    iconBg: string;
    iconFg: string;
  }
> = {
  sale: {
    icon: ShoppingBag,
    iconBg: "bg-emerald-100",
    iconFg: "text-emerald-700",
  },
  expense: {
    icon: Wallet,
    iconBg: "bg-red-100",
    iconFg: "text-red-700",
  },
  stock: {
    icon: Package,
    iconBg: "bg-amber-100",
    iconFg: "text-amber-700",
  },
};

function formatRelativeTime(iso: string): string {
  const then = new Date(iso).getTime();
  const diffSec = Math.max(0, Math.floor((Date.now() - then) / 1000));

  if (diffSec < 60) return "just now";
  const diffMin = Math.floor(diffSec / 60);
  if (diffMin < 60) return `${diffMin}m ago`;
  const diffHr = Math.floor(diffMin / 60);
  if (diffHr < 24) return `${diffHr}h ago`;
  const diffDay = Math.floor(diffHr / 24);
  if (diffDay < 7) return `${diffDay}d ago`;

  return new Date(iso).toLocaleDateString("en-LK", {
    month: "short",
    day: "numeric",
  });
}
